const colors = {
  light: {
    text: "#0A0A0A",
    tint: "#FF2D2D",
    background: "#F2F2F7",
    foreground: "#0A0A0A",
    card: "#FFFFFF",
    cardForeground: "#0A0A0A",
    primary: "#FF2D2D",
    primaryForeground: "#FFFFFF",
    secondary: "#E5E5EA",
    secondaryForeground: "#1C1C1E",
    muted: "#E5E5EA",
    mutedForeground: "#8E8E93",
    accent: "#FF2D2D",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#C6C6C8",
    input: "#E5E5EA",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#FF2D2D",
    background: "#0A0A0A",
    foreground: "#FFFFFF",
    card: "#1C1C1E",
    cardForeground: "#FFFFFF",
    primary: "#FF2D2D",
    primaryForeground: "#FFFFFF",
    secondary: "#2C2C2E",
    secondaryForeground: "#FFFFFF",
    muted: "#3A3A3C",
    mutedForeground: "#8E8E93",
    accent: "#FF2D2D",
    accentForeground: "#FFFFFF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#38383A",
    input: "#2C2C2E",
  },
  radius: 12,
};

export default colors;
